### ISSUE TITLE
Questions de compilation

### ISSUE THREAD

**Issue by trebmuh** [jpcima/ADLplug#13]
Salut @jpcima , j'ai enfin trouvé un peu de temps pour tester un empaquetage de ce logiciel.

Pour info, la version autonome jack fonctionne, la version LV2 également (testée dans jalv.select), mais la version VST fait planter Qtractor 0.9.1 .

Durant l'empaquetage, j'ai ceci à l'étape de configuration :
```
==== libADLMIDI options ====
libADLMIDI_STATIC        = ON
libADLMIDI_SHARED        = OFF
WITH_UNIT_TESTS          = OFF
WITH_CPP_EXTRAS          = OFF
WITH_MIDI_SEQUENCER      = OFF
WITH_EMBEDDED_BANKS      = ON
WITH_HQ_RESAMPLER        = OFF
WITH_MUS_SUPPORT         = OFF
WITH_XMI_SUPPORT         = OFF
USE_DOSBOX_EMULATOR      = ON
USE_NUKED_EMULATOR       = ON
===== Utils and extras =====
WITH_GENADLDATA          = OFF
WITH_GENADLDATA_COMMENTS = OFF
WITH_MIDIPLAY            = OFF
MIDIPLAY_WAVE_ONLY       = OFF
WITH_ADLMIDI2            = OFF
WITH_VLC_PLUGIN          = OFF
WITH_OLD_UTILS           = OFF
WITH_XMI2MID             = OFF
EXAMPLE_SDL2_AUDIO       = OFF
Build VST2: ON
Build VST3: OFF
Build LV2: ON
Build Standalone: ON
Build Jack: ON
```
Comme tu le vois, il y a pas mal de trucs déclarés "OFF" et je me demande si certaines de ces fonctionnalités sont activables et souhaitables. Tu pourrais m'en parler stp ?

Merci d'avance, et merci pour ce logiciel !

**Comment by jpcima** [comment]
Salut @trebmuh 

Ces options sont définies par le sous-projet `libADLMIDI` et pour la plupart elles ne sont pas modifiables en dehors du projet. Si j'en utilise quelques unes, en interne, c'est pour désactiver des fonctionnalités facultives de ADLMIDI qui ne servent à rien au plugin. Exemple : le séquenceur MIDI

S'il y en a une de semi intéressante dans ce lot, c'est `WITH_HQ_RESAMPLER`.
Son utilisation n'est pas conseillée néanmoins.

Cela active une utilisation de Zita-Resampler qui n'est pas terriblement optimisée. Ce code existe à des fins de test A/B entre un rééchantillonneur de qualité, et le rééchantillonneur tout basique de Nuked OPL. Selon moi, il n'y a pas de différence perceptible, mais libre à toi d'essayer si tu en as envie (`-DWITH_HQ_RESAMPLER=ON`).

**Comment by jpcima** [comment]
> Pour info, la version autonome jack fonctionne, la version LV2 également (testée dans jalv.select), mais la version VST fait planter Qtractor.

Tu parles de VST en version 2 ou 3 ?
(dans le doute `nm -C -D lePlugin.so | grep -w T` et envoie)

**Comment by trebmuh** [comment]
OK, merci pour les explications.

VST2 j'imagine puisque j'ai :
```
Build VST2: ON
Build VST3: OFF
```
dans le configure.

**Comment by jpcima** [comment]
OK. Faut que je teste avec ce Qtractor. Plus tard, je te tiendrai au courant.

**Comment by jpcima** [comment]
J'ai identifié la source du problème avec VST et l'hôte Qtractor.
- D'une part, il permet à l'éditeur d'être ouvert sans que le processeur d'effet soit préalablement initialisé
- Ensuite, lorsque l'éditeur est ouvert et il émet une séquence de messages au processeur, et que le processeur n'est pas en cours d'exécution, le remplissage de la file de messages peut engendrer un blocage

**Comment by trebmuh** [comment]
OK, le VST fonctionne dans Qtractor à présent.

Merci et bravo !
