### ISSUE TITLE
Please decrease cmake requirement

### ISSUE THREAD

**Issue by falkTX** [jpcima/ADLplug#18]
I was hoping to build the plugins, but can't at the moment as cmake version required is quite high.
Is there a reason for 3.5 specifically?
I often see projects having high versions for no good reason, only that they know will work and it is what they used.

**Comment by jpcima** [comment]
It's not a strict requirement, I base it on what debian uses as stable at the moment of writing it, and what support people ask me to have. It a lower version of CMake will work, I will gladly lower this requirement.
Myself I am usually on latest versions and I don't check on others very often.

**Comment by falkTX** [comment]
ah that is it indeed.
too bad juce dropping support for gcc4. I guess that means I won't be updating to it anytime soon.

**Comment by jpcima** [comment]
It is to check if this compilation can be easily made conditional. It doesn't seem to affect anything outside of Juce's `Array`.

**Comment by jpcima** [comment]
For now, I've submitted this patch to Juce which will permit a gcc4 build. https://github.com/WeAreROLI/JUCE/pull/418

**Comment by jpcima** [comment]
Update for cmake requirements: 3.3 is valid as a minimum version.
Below is not going to break the build strictly, but is going to have a negative effect: the visibility property is not going to take effect on static library targets ([CMP0063](https://cmake.org/cmake/help/v3.3/policy/CMP0063.html)).
As result, the dynamic symbol table would be polluted with all unnecessary symbols, and I've been trying to keep the exports clean on all the platforms.

**Comment by falkTX** [comment]
That seems okay then, thanks.
