### ISSUE TITLE
Questions of keyboard layouts and languages

### ISSUE THREAD

**Issue by sneakernets** [jpcima/ADLplug#25]
I haven't had a chance to use the new version yet, so excuse if this is a non issue:

When translations are added, will the keyboard layout be configurable independently of the language? The reason mainly I ask is because French Canadian keyboards are QWERTY layout. A very select few would use AZERTY. If adlplug is to get that info from the OS then, I suppose this solves itself? 

Thanks!

**Comment by jpcima** [comment]
It's not dependent on the language which is configured.
It's just too difficult to get the keyboard variant of the OS, and deduce a key map out of it.

Instead, I'm letting the user make a choice and this will be kept in the local configuration.
Now it's just two available predefinitions, but on request I can add more if someone needs.

![keyboard](https://user-images.githubusercontent.com/17614485/45783065-0c5de900-bc65-11e8-8d9d-066f0453ed38.png)
