### ISSUE TITLE
Lmms vestige menus not working

### ISSUE THREAD

**Issue by igdegoo** [jpcima/ADLplug#53]
when i load the vst plugin into lmms (latest realse) the menus (bank select, instrument select, core select) just flash for a frame and dont let me interact

video: https://youtu.be/nFY_rTdgpI4

**Comment by jpcima** [comment]
What system do you run LMMS on?
Do you attempt to load a DLL file on non-Windows OS?

**Comment by igdegoo** [comment]
> 
> 
> What system do you run LMMS on?
> Do you attempt to load a DLL file on non-Windows OS?

I am running windows 10

**Comment by jpcima** [comment]
Yes I did a quick check under a VM of Windows 7, and the problem was reproduced.
Possibly an issue of LMMS's host, I'll check if it's about plugins which are based on the same framework.

**Comment by jpcima** [comment]
@igdegoo it's definitely a LMMS host-side problem, considering JuceOPLVSTi is affected too.
I'm going to let LMMS devs know, but for now there exists a workaround to this.

Go to Edit>Settings, set Plugin Embedding = No Embedding, restart.

Then, it will operate as a separate window, and menus work expectedly. (at least on LMMS 1.2.0 RC8)

**Comment by jpcima** [comment]
The latest includes a patch as recommended by LMMS devs.
The embedding worked fine using this patched build. Please confirm.

**Comment by igdegoo** [comment]
Your fix worked

**Comment by jpcima** [comment]
:+1:
