### ISSUE TITLE
Debian : Initial « cmake -DCMAKE_BUILD_TYPE=Release ... » just fails

### ISSUE THREAD

**Issue by zebulon-1st** [jpcima/ADLplug#65]
Hello,

_I'm french, but I will use english anyway for other people._
_Use [DeepL translator](https://www.deepl.com/translator), it works fine and can really help you, with just a few knowledge of English._

_I'm not used at all with cmake. I'm an old school coder rather more used with Makefiles, gcc or clang._

- OS (uname -a) : Linux Debian 4.9.0-12-amd64 [number sign]1 SMP Debian 4.9.210-1+deb9u1 (2020-06-07) x86_64 GNU/Linux
- cmake version 3.7.2
- gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
- clang version 3.8.1-24 (tags/RELEASE_381/final)
- prerequis needed installed

---
The "clone" passed off without a hitch :
```
$ git clone --recursive https://github.com/jpcima/ADLplug.git
$ mkdir ADLplug/build
```
Then, I wanted to compile a VST2 module in order to try it in Jeskola Buzz (which runs on Windows).
But I always get the same error, even if I leave only the minimal number of options (-DCMAKE_BUILD_TYPE=Release) :
```
$ cd ADLplug/build
$ cmake -DCMAKE_BUILD_TYPE=Release -DADLplug_VST2=ON -DADLplug_Standalone=ON -DADLplug_Jack=OFF -DADLplug_CHIP=OPL3 -DADLplug_PCH=OFF -DADLplug_ASSERTIONS=ON
CMake Error: The source directory "ADLplug/build" does not appear to contain CMakeLists.txt.
```
What did I miss ?

**Comment by jpcima** [comment]
Hello @zebulon-1st 
It needs `..` at the end of the cmake line.
A priori the rest looks OK.

**Comment by zebulon-1st** [comment]
>It needs `..` at the end of the cmake line.

Oh.
Thx. ;)
