### ISSUE TITLE
Wave file export for standalone?

### ISSUE THREAD

**Issue by kirkmarkarian** [jpcima/ADLplug#71]
I enjoy using the Mac standalone version of this synth, and my main sequencer is Renoise.  I’d like to use this as a sample generator to take advantage of the sampler in Renoise versus using this as a plugin (using more processor power).  Is there any way to use the standalone to do such a thing, besides setting up Audacity or a different program to capture myself “jamming”? 😄

**Comment by jpcima** [comment]
Hi @kirkmarkarian.
It's a feature that is not likely to happen, and feels out of scope of what this synth is.
I'm sure that there exist some external programs which will do sample recording and editing, way better that I could implement myself in short term. (that includes capture, cutting, looping, etc)

**Comment by kirkmarkarian** [comment]
No problem at all - I use Audio Hijack to capture a note, then I cut out a single-cycle from Renoise.  Works fine!  In any case, it's great to relive my memories of OPL2/3 synthesis!  Thank you for making these :)
