### ISSUE TITLE
-- Package 'jack', required by 'virtual:world', not found

### ISSUE THREAD

**Issue by aljohnston112** [jpcima/ADLplug#80]
I am trying to build on Fedora. I have Jack-audio-connection-kit and qjackctl installed. pkg_check_modules(JACK jack REQUIRED) is the cmake line that fails. I do not know how to make pkg_check_modules succeed.

**Comment by jpcima** [comment]
Hi @aljohnston112 
I believe it wants the package `jack-audio-connection-kit-devel`.

**Comment by aljohnston112** [comment]
It did want the devel package. Thank you.
